version: '3'
services:
  inferno:
    build:
      context: ./
    volumes:
      - ./data:/opt/inferno/data
    depends_on:
      - validator-service
  worker:
    build:
      context: ./
    volumes:
      - ./data:/opt/inferno/data
    command: bundle exec sidekiq -r ./worker.rb
    depends_on:
      - redis
  validator-service:
    extends:
      file: docker-compose.background.yml
      service: validator-service
  fhir-validator-app:
    extends:
      file: docker-compose.background.yml
      service: fhir-validator-app
  nginx:
    extends:
      file: docker-compose.background.yml
      service: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
  redis:
    extends:
      file: docker-compose.background.yml
      service: redis
